### ISSUE TITLE
Is there any plan for continuing the support of EPID based attestation?

### ISSUE THREAD

**Issue by Ruide** [mc2-project/opaque#119]
Hi,

Good morning! I notice the current version only supports openenclave sdk based DCAP attestation. However,  machines without FLC can only support EPID based attestation. I wonder if I want to continue taking advantage of EPID based attestation, shall I convert back to commits before merge #92 and start my own fork? Or shall I change the existing branch? Or is there a better way in your opinion?

Thank you!

**Comment by wzheng** [comment]
Hi Ruide -- sorry for the late reply, but if you haven't done so, please try an earlier version of the code if you want to use the older attestation method.
